# Generated by Django 5.1.6 on 2025-06-28 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2'), ('Funded', 'Funded')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profit_target', models.DecimalField(decimal_places=2, default=800.0, max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=1200.0, max_digits=12)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Completado', 'Completado')], default='Activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='EUR/USD', max_length=10)),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.tradingaccount')),
            ],
        ),
    ]
