# Generated by Django 5.1.6 on 2025-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_trade_stop_loss_trade_take_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='tier',
            field=models.CharField(choices=[('10K', 'Cuenta 10 000'), ('50K', 'Cuenta 50 000'), ('100K', 'Cuenta 100 000')], default='10K', help_text='Elige el plan de fondeo', max_length=4),
        ),
    ]
