# Generated by Django 5.1.6 on 2025-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_tradingaccount_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='phase',
            field=models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2'), ('Funded', 'Funded')], default='Fase 1', max_length=20),
        ),
    ]
