# Generated by Django 5.1.6 on 2025-07-22 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_tradingaccount_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='tier',
            field=models.CharField(choices=[('10K', 'Cuenta 10\u2009000'), ('50K', 'Cuenta 50\u2009000'), ('100K', 'Cuenta 100\u2009000')], default='10K', help_text='Elige el plan de fondeo', max_length=4),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('10K', 'Cuenta 10\u2009000'), ('50K', 'Cuenta 50\u2009000'), ('100K', 'Cuenta 100\u2009000')], help_text='El plan que el usuario compró', max_length=4)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
