# Generated by Django 5.1.6 on 2025-08-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_tradingaccount_tier_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='leverage',
            field=models.PositiveIntegerField(default=50, help_text='Apalancamiento (p. ej. 50 = 1:50)'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='margin_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='netting_mode',
            field=models.BooleanField(default=True, help_text='True = netting (una posición abierta por símbolo/side). False = hedging (múltiples).'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='pnl_unreal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='EUR/USD', max_length=12)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('trail_dist', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('best_price', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=6)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client_order_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='simulator.tradingaccount')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='simulator.position'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['account', 'symbol'], name='simulator_p_account_c7b3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['account', 'status'], name='simulator_p_account_f401aa_idx'),
        ),
        # ❌ Se eliminó el AddConstraint con account__netting_mode porque usa join
    ]