# Generated by Django 5.1.6 on 2025-08-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_tradingaccount_leverage_tradingaccount_margin_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('COMMISSION', 'COMMISSION'), ('REALIZED_PNL', 'REALIZED_PNL'), ('FEE', 'FEE'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # ❌ Quitamos RemoveConstraint porque ese constraint no existe
        migrations.RemoveIndex(
            model_name='position',
            name='simulator_p_account_f401aa_idx',
        ),
        migrations.RemoveField(
            model_name='position',
            name='best_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='client_order_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='position',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='position',
            name='trail_dist',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='margin_used',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='pnl_unreal',
        ),
        migrations.AddField(
            model_name='position',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='qty',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='position',
            name='sl',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='tp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=6),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='EUR/USD', max_length=12),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='leverage',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='netting_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='simulator.tradingaccount'),
        ),
    ]