# Generated by Django 5.1.6 on 2025-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_ledgerentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='netting_mode',
            field=models.BooleanField(default=True, help_text='True=Netting (consolidar por símbolo); False=Hedging (varias posiciones).'),
        ),
    ]
