# Generated by Django 5.1.6 on 2025-08-16 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_alter_ledgerentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-opened_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-opened_at', '-id']},
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='daily_loss_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='env',
            field=models.CharField(choices=[('SIM', 'Simulador / Demo'), ('CHALLENGE', 'Challenge (Fase 1/2)'), ('FUNDED', 'Funded (con reglas)'), ('LIVE', 'Broker Live')], default='SIM', help_text='Contexto operativo de la cuenta', max_length=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='ruleset',
            field=models.CharField(blank=True, help_text='Nombre del set de reglas (p.ej. standard_v1)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('COMMISSION', 'COMMISSION'), ('REALIZED_PNL', 'REALIZED_PNL'), ('FEE', 'FEE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('FORCED_CLOSE', 'FORCED_CLOSE')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'event_type'], name='simulator_l_account_201c37_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['created_at'], name='simulator_l_created_d04647_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['account', 'symbol', 'side'], name='simulator_p_account_3e6907_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'tier'], name='simulator_p_user_id_5d44ce_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['used'], name='simulator_p_used_c2c8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'symbol'], name='simulator_t_account_f05b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['opened_at'], name='simulator_t_opened__257070_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['user', 'env'], name='simulator_t_user_id_fb4628_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['status'], name='simulator_t_status_39ead5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['created_at'], name='simulator_t_created_3f05dc_idx'),
        ),
    ]
