# Generated by Django 5.1.6 on 2025-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_alter_position_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='simulator_l_account_201c37_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='simulator_l_created_d04647_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='simulator_p_account_3e6907_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='simulator_p_user_id_5d44ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='simulator_p_used_c2c8c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='simulator_t_account_f05b9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='simulator_t_opened__257070_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradingaccount',
            name='simulator_t_user_id_fb4628_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradingaccount',
            name='simulator_t_status_39ead5_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradingaccount',
            name='simulator_t_created_3f05dc_idx',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='daily_loss_limit',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='env',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='rules_accepted_at',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='ruleset',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('COMMISSION', 'COMMISSION'), ('REALIZED_PNL', 'REALIZED_PNL'), ('FEE', 'FEE'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=16),
        ),
    ]
