# Generated by Django 5.1.6 on 2026-05-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0010_alter_position_options_alter_purchase_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "crypto_currency",
                    models.CharField(
                        choices=[
                            ("btc", "Bitcoin (BTC)"),
                            ("eth", "Ethereum (ETH)"),
                            ("usdttrc20", "USDT TRC-20"),
                            ("usdterc20", "USDT ERC-20"),
                            ("sol", "Solana (SOL)"),
                            ("bnbmainnet", "BNB (BSC)"),
                            ("usdcsol", "USDC (Solana)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nowpayments_payment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "nowpayments_invoice_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("waiting", "Esperando pago"),
                            ("confirming", "Confirmando"),
                            ("confirmed", "Confirmado"),
                            ("sending", "Enviando"),
                            ("partially_paid", "Pago parcial"),
                            ("finished", "Completado"),
                            ("failed", "Fallido"),
                            ("refunded", "Reembolsado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
