# Generated by Django 5.1.6 on 2026-05-07 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0011_add_deposit_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="opened_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
