# Generated by Django 5.1.6 on 2026-05-15 16:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0018_dynamic_account_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("RETAIL", "Retail"),
                    ("ECN", "ECN"),
                    ("STANDARD", "Standard"),
                    ("DEMO", "Demo"),
                    ("CRYPTO", "Crypto"),
                    ("CHALLENGE", "Challenge"),
                    ("FUNDED", "Funded"),
                ],
                default="CHALLENGE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=6)),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("WALLET_TO_ACCOUNT", "Wallet → Trading Account"),
                            ("ACCOUNT_TO_WALLET", "Trading Account → Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trading_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transfers",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="simulator.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Wallet from which this account was funded",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trading_accounts",
                to="simulator.wallet",
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("TRANSFER_OUT", "Transfer Out (→ Account)"),
                            ("TRANSFER_IN", "Transfer In (← Account)"),
                            ("BONUS", "Bonus"),
                            ("REBATE", "Rebate"),
                            ("COMMISSION", "Commission"),
                            ("CORRECTION", "Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=18)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_txs",
                        to="simulator.deposit",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_txs",
                        to="simulator.internaltransfer",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="simulator.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="wallet_user_idx"),
        ),
        migrations.AddIndex(
            model_name="internaltransfer",
            index=models.Index(
                fields=["wallet", "status"], name="itx_wallet_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internaltransfer",
            index=models.Index(
                fields=["trading_account", "status"], name="itx_acc_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internaltransfer",
            index=models.Index(fields=["created_at"], name="itx_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "created_at"], name="wtx_wallet_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["tx_type", "created_at"], name="wtx_type_ts_idx"
            ),
        ),
    ]
