# Generated by Django 5.1.6 on 2026-05-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0019_wallet_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="credited",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="deposit",
            name="credited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
