# Generated by Django 5.1.6 on 2026-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0020_deposit_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="confirmed_amount_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="pay_address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="pay_amount",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=24, null=True
            ),
        ),
    ]
