# Generated by Django 5.1.6 on 2026-05-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0021_deposit_payment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="crypto_currency",
            field=models.CharField(
                choices=[
                    ("btc", "Bitcoin (BTC)"),
                    ("eth", "Ethereum (ETH)"),
                    ("usdttrc20", "USDT TRC-20"),
                    ("usdterc20", "USDT ERC-20"),
                    ("sol", "Solana (SOL)"),
                    ("xrp", "XRP"),
                    ("bnbbsc", "BNB (BEP-20)"),
                    ("usdcsol", "USDC (Solana)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "crypto_currency",
                    models.CharField(
                        choices=[
                            ("btc", "Bitcoin (BTC)"),
                            ("eth", "Ethereum (ETH)"),
                            ("usdttrc20", "USDT TRC-20"),
                            ("sol", "Solana (SOL)"),
                            ("bnbbsc", "BNB (BEP-20)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wallet_address", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "np_batch_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "np_payout_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "np_payout_status",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "crypto_amount",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("admin_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit_tx",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_request",
                        to="simulator.wallettransaction",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="wr_user_status_idx"),
                    models.Index(fields=["created_at"], name="wr_created_at_idx"),
                ],
            },
        ),
    ]
