# Generated by Django 5.1.6 on 2026-05-17 18:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0022_withdrawal_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerEquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField(db_index=True)),
                ("active_accounts", models.PositiveIntegerField(default=0)),
                ("open_positions", models.PositiveIntegerField(default=0)),
                (
                    "total_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "floating_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_margin_used",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_free_margin",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "gross_long_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "gross_short_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_exposure_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Equity Snapshot",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(fields=["taken_at"], name="brokerequitysnap_ts_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountEquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "floating_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "margin_used",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "free_margin",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "drawdown",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                ("open_positions", models.PositiveSmallIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_snapshots",
                        to="simulator.tradingaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Equity Snapshot",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "taken_at"], name="accequitysnap_acc_ts_idx"
                    ),
                    models.Index(fields=["taken_at"], name="accequitysnap_ts_idx"),
                ],
            },
        ),
    ]
