# Generated by Django 5.1.6 on 2026-05-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0027_tradingaccount_netting_default_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue_type",
                    models.CharField(
                        choices=[
                            ("COMMISSION", "Commission"),
                            ("SPREAD", "Spread"),
                            ("CHALLENGE_FEE", "Challenge Fee"),
                            ("WITHDRAW_FEE", "Withdrawal Fee"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("symbol", models.CharField(blank=True, max_length=12, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_ledger",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "source_ledger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_ledger",
                        to="simulator.ledgerentry",
                    ),
                ),
                (
                    "source_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broker_ledger",
                        to="simulator.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
