# Generated by Django 5.1.6 on 2026-05-24 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0028_broker_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerSpreadConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "spread_pips",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Additional markup per side in pips (1 pip = spec.pip_size for the symbol).",
                        max_digits=8,
                    ),
                ),
                (
                    "is_dynamic",
                    models.BooleanField(
                        default=False,
                        help_text="Reserved for future dynamic/session spread logic.",
                    ),
                ),
                (
                    "min_spread",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.50"), max_digits=8
                    ),
                ),
                (
                    "max_spread",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=8
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
    ]
