# Generated by Django 5.1.6 on 2026-06-01 19:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0031_broker_revenue_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("DEMO", "Demo"),
                            ("RETAIL", "Retail / USDT"),
                            ("ECN", "ECN"),
                            ("STANDARD", "Standard"),
                            ("CRYPTO", "Crypto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "min_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=12
                    ),
                ),
                ("max_leverage", models.PositiveIntegerField(default=50)),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                (
                    "spread_markup",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=5
                    ),
                ),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Account Product",
                "ordering": ["product_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("10K", "$10,000"),
                            ("25K", "$25,000"),
                            ("50K", "$50,000"),
                            ("100K", "$100,000"),
                        ],
                        max_length=6,
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("account_size", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "p1_profit_target_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.00"), max_digits=5
                    ),
                ),
                (
                    "p1_max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "p1_max_daily_loss_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                ("p1_min_trading_days", models.PositiveIntegerField(default=5)),
                ("p1_max_duration_days", models.PositiveIntegerField(default=30)),
                (
                    "p2_profit_target_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "p2_max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "p2_max_daily_loss_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                ("p2_min_trading_days", models.PositiveIntegerField(default=5)),
                ("p2_max_duration_days", models.PositiveIntegerField(default=60)),
                (
                    "profit_split_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80.00"), max_digits=5
                    ),
                ),
                (
                    "max_lot_size",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=8
                    ),
                ),
                ("max_open_positions", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Challenge Product",
                "ordering": ["tier", "price_usd"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PHASE_1", "Phase 1 — Active"),
                            ("PHASE_2", "Phase 2 — Active"),
                            ("FUNDED", "Funded"),
                            ("FAILED", "Failed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PHASE_1",
                        max_length=12,
                    ),
                ),
                (
                    "failed_at_phase",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("phase1_passed_at", models.DateTimeField(blank=True, null=True)),
                ("phase2_passed_at", models.DateTimeField(blank=True, null=True)),
                ("funded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenge_enrollments",
                        to="simulator.deposit",
                    ),
                ),
                (
                    "funded_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_funded",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "phase1_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_phase1",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "phase2_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_phase2",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="simulator.challengeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Enrollment",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="FundedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funded_type",
                    models.CharField(
                        choices=[
                            ("FUNDED_SIM", "Simulation Funded — virtual capital"),
                            (
                                "FUNDED_INTERNAL",
                                "Internal Funded — firm capital assigned",
                            ),
                        ],
                        default="FUNDED_SIM",
                        max_length=16,
                    ),
                ),
                (
                    "profit_split_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "min_payout_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                ("min_trading_days", models.PositiveIntegerField(default=5)),
                ("payout_cycle_days", models.PositiveIntegerField(default=14)),
                (
                    "max_monthly_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funded_config",
                        to="simulator.challengeenrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funded Account Config",
            },
        ),
        migrations.AddIndex(
            model_name="challengeenrollment",
            index=models.Index(
                fields=["user", "status"], name="enrollment_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deposit__isnull", False)),
                fields=("deposit",),
                name="unique_enrollment_per_deposit",
            ),
        ),
    ]
