# Generated by Django 5.1.6 on 2026-06-02 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulator",
            "0032_accountproduct_challengeproduct_challengeenrollment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="challenge_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposits",
                to="simulator.challengeproduct",
            ),
        ),
    ]
