# Generated by Django 5.1.6 on 2026-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0033_deposit_challenge_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeenrollment",
            name="external_event_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="challengeenrollment",
            name="external_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="challengeproduct",
            name="external_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
