# Generated by Django 5.1.6 on 2026-06-05 23:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0034_external_challenge_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountproduct",
            options={
                "ordering": ["family", "sort_order", "name"],
                "verbose_name": "Account Product",
            },
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="commission_per_lot",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="default_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="family",
            field=models.CharField(
                choices=[("DEMO", "Demo"), ("REAL", "Real")],
                default="REAL",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="platform_label",
            field=models.CharField(default="Money Broker", max_length=64),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountproduct",
            name="typical_spread_pips",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="accountproduct",
            name="max_leverage",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
