# Generated by Django 5.1.6 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0041_funded_payout_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "DEPOSIT"),
                    ("WITHDRAW", "WITHDRAW"),
                    ("COMMISSION", "COMMISSION"),
                    ("REALIZED_PNL", "REALIZED_PNL"),
                    ("FEE", "FEE"),
                    ("ADJUSTMENT", "ADJUSTMENT"),
                    ("FUNDED_PAYOUT", "Funded Payout"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("TRANSFER_OUT", "Transfer Out (→ Account)"),
                    ("TRANSFER_IN", "Transfer In (← Account)"),
                    ("BONUS", "Bonus"),
                    ("REBATE", "Rebate"),
                    ("COMMISSION", "Commission"),
                    ("CORRECTION", "Correction"),
                    ("FUNDED_PAYOUT", "Funded Payout (← Funded Account)"),
                ],
                max_length=20,
            ),
        ),
    ]
