# Generated by Django 5.1.6 on 2026-07-11 03:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0042_alter_ledgerentry_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Compact ticker, e.g. 'EURUSD', 'BTCUSD'.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable form, e.g. 'EUR/USD'.", max_length=32
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("forex", "Forex"),
                            ("metal", "Metal"),
                            ("energy", "Energy"),
                            ("crypto", "Crypto"),
                            ("index", "Index"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("base_currency", models.CharField(max_length=8)),
                ("quote_currency", models.CharField(default="USD", max_length=8)),
                (
                    "pip_size",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.0001"), max_digits=14
                    ),
                ),
                (
                    "tick_size",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.00001"), max_digits=14
                    ),
                ),
                ("price_decimals", models.PositiveSmallIntegerField(default=5)),
                (
                    "lot_step",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.01"), max_digits=10
                    ),
                ),
                (
                    "min_lot",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.01"), max_digits=10
                    ),
                ),
                (
                    "max_lot",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                (
                    "contract_size",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("100000.0000"), max_digits=16
                    ),
                ),
                (
                    "default_spread",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Typical spread, expressed in spread_unit.",
                        max_digits=10,
                    ),
                ),
                (
                    "spread_unit",
                    models.CharField(
                        choices=[
                            ("pips", "Pips"),
                            ("points", "Points"),
                            ("percent", "Percent"),
                        ],
                        default="pips",
                        max_length=8,
                    ),
                ),
                (
                    "commission_per_lot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=9
                    ),
                ),
                ("max_leverage", models.PositiveIntegerField(default=100)),
                (
                    "margin_mode",
                    models.CharField(
                        choices=[
                            ("leverage", "Leverage-based"),
                            ("percent", "Fixed percentage"),
                        ],
                        default="leverage",
                        max_length=16,
                    ),
                ),
                (
                    "pnl_mode",
                    models.CharField(
                        choices=[
                            (
                                "STANDARD",
                                "Standard (quote currency = account currency)",
                            ),
                            (
                                "INVERSE",
                                "Inverse (quote currency differs, requires conversion)",
                            ),
                        ],
                        default="STANDARD",
                        max_length=16,
                    ),
                ),
                (
                    "market_data_provider",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("kraken", "Kraken"),
                            ("finnhub", "Finnhub"),
                            ("sim", "Simulated"),
                        ],
                        default="sim",
                        max_length=16,
                    ),
                ),
                (
                    "provider_symbol",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-specific symbol, e.g. 'FX:EURUSD', 'BTCUSDT'.",
                        max_length=32,
                    ),
                ),
                ("trading_enabled", models.BooleanField(db_index=True, default=False)),
                (
                    "session",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Trading session hours, e.g. '24/5', '24/7'.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "ordering": ["asset_class", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["asset_class", "trading_enabled"],
                        name="instr_class_enabled_idx",
                    )
                ],
            },
        ),
    ]
