# Generated by Django 5.1.6 on 2026-07-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0043_instrument"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="pricing_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="pricing_context_close",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="pricing_context_open",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
