# Generated by Django 5.1.6 on 2026-07-13 21:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0044_pricing_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeproduct",
            name="commission_pct",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="challengeproduct",
            name="commission_per_lot",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="challengeproduct",
            name="max_spread_pips",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="challengeproduct",
            name="min_spread_pips",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="challengeproduct",
            name="spread_markup_pips",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="commercial_profile_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        # ── Corrective, pre-commit: BrokerSpreadConfig.min_spread/max_spread
        # were defined with economic defaults (0.50/5.00) that this same
        # migration's SPREAD-04 work turns into a REAL clamp for the first
        # time (previously decorative — see spread_config_cache.py). A
        # symbol like BTCUSD with a realistic 15-pip base spread would be
        # silently narrowed to 5 pips the moment this migration runs,
        # purely because of an arbitrary model default, not any admin
        # decision. Fix: bounds become opt-in via spread_bounds_enabled
        # (new field, default False) and min/max become nullable with no
        # default. Existing rows keep whatever min_spread/max_spread value
        # they already have — untouched — but that value is now inert
        # (never read) until an admin explicitly flips spread_bounds_enabled
        # to True. No existing row's effective price changes.
        migrations.AddField(
            model_name="brokerspreadconfig",
            name="spread_bounds_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "min_spread/max_spread below are IGNORED unless this is on. "
                    "Defaults to off so no existing or historical row silently "
                    "clamps a symbol's spread — an admin must opt in explicitly."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="brokerspreadconfig",
            name="min_spread",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True,
                help_text="Floor in pips. Null = no floor. Applied only when spread_bounds_enabled is on.",
            ),
        ),
        migrations.AlterField(
            model_name="brokerspreadconfig",
            name="max_spread",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True,
                help_text="Ceiling in pips. Null = no ceiling. Applied only when spread_bounds_enabled is on.",
            ),
        ),
    ]
