# Generated by Django 5.1.6 on 2026-07-14 05:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0045_commercial_pricing_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerspreadconfig",
            name="manual_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set and in the past, manual_multiplier is treated as 1.000 (expired).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="brokerspreadconfig",
            name="manual_multiplier",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                help_text="Manual override multiplier applied on top of the dynamic chain. Only has any effect when is_dynamic=True, the value is > 0, and manual_expires_at (if set) has not passed. 1.000 = no override.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="brokerspreadconfig",
            name="manual_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text audit note for why manual_multiplier was set. Never affects pricing.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="brokerspreadconfig",
            name="is_dynamic",
            field=models.BooleanField(
                default=False,
                help_text="SPREAD-05 opt-in: when on, effective spread is computed by the Dynamic Spread Engine (session/source/staleness/volatility/liquidity/manual multipliers on top of spread_pips+markup). When off (default), behavior is identical to SPREAD-04 — this flag alone controls the dynamic path, no separate flag needed.",
            ),
        ),
    ]
