# Generated by Django 5.1.6 on 2026-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0046_dynamic_spread_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="pnl_conversion",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
