# Generated by Django 5.1.6 on 2026-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0047_trade_pnl_conversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerledger",
            name="revenue_type",
            field=models.CharField(
                choices=[
                    ("COMMISSION", "Commission"),
                    ("SPREAD", "Spread"),
                    ("CHALLENGE_FEE", "Challenge Fee"),
                    ("WITHDRAW_FEE", "Withdrawal Fee"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("COUNTERPARTY_PNL", "Counterparty PnL (B-Book)"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="brokerledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_trade__isnull", False)),
                fields=("source_trade", "revenue_type"),
                name="uniq_brokerledger_source_trade_revenue_type",
            ),
        ),
    ]
