# Generated by Django 5.1.6 on 2026-07-17 16:59

from django.db import migrations, models


def seed_singleton_row(apps, schema_editor):
    """RISK-02 — the whole point of this model is a single contention
    point; create the one row (id=1) it will ever need, here, so no
    runtime code has to get_or_create it under a race."""
    BrokerRiskLock = apps.get_model("simulator", "BrokerRiskLock")
    BrokerRiskLock.objects.get_or_create(id=1)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0048_book02_counterparty_pnl"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerRiskLock",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_singleton_row, noop_reverse),
    ]
