# Generated by Django 5.1.6 on 2026-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0049_risk02_broker_risk_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerrisklock",
            name="last_recreated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
