# Generated by Django 5.1.6 on 2026-07-18 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0050_risk03_broker_risk_lock_last_recreated"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("category", models.CharField(db_index=True, max_length=20)),
                ("severity", models.CharField(db_index=True, max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_type", models.CharField(db_index=True, max_length=20)),
                ("actor_id", models.PositiveIntegerField(blank=True, null=True)),
                ("symbol", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source_module", models.CharField(blank=True, max_length=80)),
                ("request_id", models.CharField(blank=True, max_length=40)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="simulator.tradingaccount",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="simulator.trade",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["account", "-timestamp"],
                        name="audit_evt_account_ts_idx",
                    ),
                    models.Index(
                        fields=["trade", "-timestamp"], name="audit_evt_trade_ts_idx"
                    ),
                    models.Index(
                        fields=["symbol", "-timestamp"], name="audit_evt_symbol_ts_idx"
                    ),
                    models.Index(
                        fields=["category", "-timestamp"],
                        name="audit_evt_category_ts_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="audit_evt_severity_ts_idx",
                    ),
                ],
            },
        ),
    ]
