# Generated by Django 5.1.6 on 2026-07-18 03:00

from django.db import migrations, models


def seed_singleton_row(apps, schema_editor):
    """AUDIT-01 correction — same seeding discipline as RISK-02's
    BrokerRiskLock: create the one row (id=1) this mutex will ever need
    here, so runtime code has to get_or_create it under a race."""
    BrokerAuditObservationLock = apps.get_model("simulator", "BrokerAuditObservationLock")
    BrokerAuditObservationLock.objects.get_or_create(id=1)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0051_audit01_broker_audit_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerAuditObservationLock",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_singleton_row, noop_reverse),
    ]
