# Generated by Django 5.1.6 on 2026-07-21 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0052_audit01_fix_observation_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerauditevent',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerauditevent',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simulator.deposit'),
        ),
        migrations.AddField(
            model_name='brokerauditevent',
            name='event_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='brokerauditevent',
            name='funded_payout_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simulator.fundedpayoutrequest'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='fundedpayoutrequest',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='brokerauditevent',
            index=models.Index(fields=['funded_payout_request', '-timestamp'], name='audit_evt_fpr_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerauditevent',
            index=models.Index(fields=['deposit', '-timestamp'], name='audit_evt_deposit_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerauditevent',
            index=models.Index(fields=['correlation_id'], name='audit_evt_correlation_idx'),
        ),
    ]
