# Generated by Django 5.1.6 on 2026-07-23 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0054_audit03_kyc_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('book', models.CharField(db_index=True, max_length=20)),
                ('reason_code', models.CharField(db_index=True, max_length=60)),
                ('reason_message', models.CharField(blank=True, default='', max_length=240)),
                ('engine_version', models.PositiveSmallIntegerField(default=1)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inputs_snapshot', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.CharField(blank=True, default='', max_length=120)),
                ('override_reason', models.CharField(blank=True, default='', max_length=240)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_decisions', to='simulator.routingdecision')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
                'get_latest_by': 'decided_at',
                'indexes': [models.Index(fields=['book', '-decided_at'], name='routing_dec_book_ts_idx'), models.Index(fields=['reason_code', '-decided_at'], name='routing_dec_reason_ts_idx'), models.Index(fields=['correlation_id'], name='routing_dec_correlation_idx')],
            },
        ),
    ]
