# Generated by Django 5.1.6 on 2026-07-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0055_book04a_routing_decision_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='routing_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simulator.routingdecision'),
        ),
        migrations.AddField(
            model_name='routingdecision',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_decisions', to='simulator.position'),
        ),
    ]
