# Generated by Django 5.1.6 on 2026-07-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0056_book04b_position_routing_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='routing_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simulator.routingdecision'),
        ),
    ]
