# Generated by Django 5.1.6 on 2026-07-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0057_book04c_trade_routing_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingdecision',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_decisions', to='simulator.tradingaccount'),
        ),
    ]
