# Generated by Django 5.1.6 on 2026-07-25 01:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0058_book04e_routing_decision_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbols_covered', models.JSONField(blank=True, default=list)),
                ('simulated_spread_markup_pips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('max_capacity_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=12)),
                ('exposure_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('simulated_spread', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('simulated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('inputs_snapshot', models.JSONField(blank=True, default=dict)),
                ('engine_version', models.PositiveSmallIntegerField(default=1)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidity_decisions', to='simulator.position')),
                ('routing_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidity_decisions', to='simulator.routingdecision')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='simulator.liquidityprovider')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
                'indexes': [models.Index(fields=['symbol', '-decided_at'], name='liquidity_dec_symbol_ts_idx'), models.Index(fields=['provider', '-decided_at'], name='liquidity_dec_provider_ts_idx')],
            },
        ),
    ]
