# Generated by Django 5.1.6 on 2026-07-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0059_book05a_liquidity_provider_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=12)),
                ('simulated_pnl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('liquidity_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='simulator.liquiditydecision')),
                ('source_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidity_ledger', to='simulator.trade')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='liquidity_ledger_symbol_ts_idx'), models.Index(fields=['liquidity_decision', '-created_at'], name='liquidity_ledger_dec_ts_idx')],
            },
        ),
    ]
