# Generated by Django 5.1.6 on 2026-07-27 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0060_book05d_liquidity_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealingDeskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=12)),
                ('is_simulated_hedge', models.BooleanField(default=False)),
                ('routing_profile_snapshot', models.CharField(db_index=True, max_length=20)),
                ('engine_version', models.PositiveSmallIntegerField(default=1)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('liquidity_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealing_desk_decisions', to='simulator.liquiditydecision')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealing_desk_decisions', to='simulator.position')),
                ('routing_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealing_desk_decisions', to='simulator.routingdecision')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
                'indexes': [models.Index(fields=['symbol', '-decided_at'], name='ddesk_dec_symbol_ts_idx'), models.Index(fields=['routing_decision', '-decided_at'], name='ddesk_dec_routing_ts_idx')],
            },
        ),
    ]
