# Generated by Django 5.1.6 on 2026-07-30 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0061_book06a_dealing_desk_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryOperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREDIT_FUNDS', 'Credit Funds'), ('DEBIT_FUNDS', 'Debit Funds'), ('REFUND', 'Refund'), ('BONUS_CREDIT', 'Bonus Credit'), ('IB_COMMISSION', 'IB / Referral Commission'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, choices=[('SYSTEM_ERROR', 'System Error'), ('PROVIDER_DUPLICATE', 'Provider Duplicate'), ('INCIDENT_COMPENSATION', 'Incident Compensation'), ('OTHER', 'Other')], default='', max_length=40)),
                ('comment', models.TextField(blank=True, default='')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='treasury/evidence/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_requests_executed', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_requests_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_requests_made', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_requests', to='simulator.wallet')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_request', to='simulator.wallettransaction')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'permissions': [('can_review_treasury_request', 'Can review (approve/reject) treasury request'), ('can_execute_treasury_request', 'Can execute treasury request')],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='treasury_req_status_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='treasury_request_amount_positive')],
            },
        ),
    ]
