# Generated by Django 5.1.6 on 2026-07-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0062_o2g1_treasury_operation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoperationrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
