# Generated by Django 5.1.6 on 2026-07-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0063_o2g1a_treasury_request_cancelled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasuryoperationrequest',
            options={'ordering': ['-requested_at', '-id'], 'permissions': [('can_submit_treasury_request', 'Can submit (create) treasury request'), ('can_review_treasury_request', 'Can review (approve/reject) treasury request'), ('can_execute_treasury_request', 'Can execute treasury request')]},
        ),
    ]
