# Generated by Django 5.1.6 on 2026-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0064_o3a1_treasury_can_submit_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryoperationrequest',
            name='operation_type',
            field=models.CharField(choices=[('CREDIT_FUNDS', 'Credit Funds'), ('DEBIT_FUNDS', 'Debit Funds'), ('REFUND', 'Refund'), ('BONUS_CREDIT', 'Bonus Credit'), ('IB_COMMISSION', 'IB / Referral Commission'), ('MANUAL_CREDIT', 'Manual Credit Adjustment'), ('MANUAL_DEBIT', 'Manual Debit Adjustment')], db_index=True, max_length=20),
        ),
    ]
