# Generated by Django 5.1.6 on 2026-08-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0065_o3c0a_manual_adjustment_split'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasuryoperationrequest',
            options={'ordering': ['-requested_at', '-id'], 'permissions': [('can_submit_treasury_request', 'Can submit (create) treasury request'), ('can_review_treasury_request', 'Can review (approve/reject) treasury request'), ('can_execute_treasury_request', 'Can execute treasury request'), ('can_recover_treasury_execution', 'Can recover (mark failed) stuck treasury execution')]},
        ),
    ]
