# Generated by Django 5.1.6 on 2026-08-14 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0066_o3c4c_treasury_can_recover_execution_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproduct',
            name='max_margin_per_trade_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='accountproduct',
            name='max_total_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='max_margin_per_trade_pct_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='max_total_margin_pct_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
