# Generated by Django 5.1.6 on 2026-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0067_o6c1e_configurable_margin_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproduct',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
