# Generated by Django 5.1.6 on 2026-08-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0068_o6c1g_account_product_features_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderscore',
            name='candidate_routing_profile',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('REVIEW', 'Review'), ('HEDGE_CANDIDATE', 'Hedge Candidate'), ('ELITE', 'Elite')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='candidate_streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='routing_profile_engine_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='routing_profile_evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='v2_routing_profile',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('REVIEW', 'Review'), ('HEDGE_CANDIDATE', 'Hedge Candidate'), ('ELITE', 'Elite')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='v2_routing_profile_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
