# Generated by Django 5.1.6 on 2026-08-26 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0069_book06k1_routing_profile_policy_v2_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('attempt_number', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('requested_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_asset', models.CharField(max_length=20)),
                ('requested_network', models.CharField(blank=True, default='', max_length=20)),
                ('destination_address', models.CharField(max_length=200)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown')], db_index=True, default='created', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('raw_provider_status', models.CharField(blank=True, default='', max_length=40)),
                ('reconciliation_checked_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payout_attempts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payout_attempts', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_attempts', to='simulator.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['withdrawal_request', 'status'], name='pa_wr_status_idx'), models.Index(fields=['created_at'], name='pa_created_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('withdrawal_request', 'attempt_number'), name='pa_unique_wr_attempt_number'), models.UniqueConstraint(condition=models.Q(('status__in', ('created', 'submitted', 'processing', 'unknown'))), fields=('withdrawal_request',), name='pa_one_active_attempt_per_wr')],
            },
        ),
    ]
