# Generated by Django 5.1.6 on 2026-08-27 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0070_fix02a1_payout_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_fingerprint', models.CharField(max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('raw_status', models.CharField(blank=True, default='', max_length=40)),
                ('normalized_status', models.CharField(blank=True, default='', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('manual_review', 'Manual Review')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='payoutattempt',
            name='provider_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='payoutattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_request_id', ''), _negated=True), fields=('provider', 'provider_request_id'), name='pa_unique_provider_request_id'),
        ),
        migrations.AddField(
            model_name='payoutwebhookevent',
            name='correlated_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='simulator.payoutattempt'),
        ),
        migrations.AddIndex(
            model_name='payoutwebhookevent',
            index=models.Index(fields=['provider', 'correlation_status'], name='pwe_provider_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutwebhookevent',
            index=models.Index(fields=['provider_reference'], name='pwe_provider_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutwebhookevent',
            index=models.Index(fields=['provider_batch_id'], name='pwe_provider_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutwebhookevent',
            index=models.Index(fields=['correlation_status', 'next_retry_at'], name='pwe_status_next_retry_idx'),
        ),
    ]
