# Generated by Django 5.1.6 on 2026-08-28 00:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0071_fix02a4_payout_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproduct',
            name='stopout_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5),
        ),
    ]
