# Generated by Django 5.1.6 on 2026-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0072_fix03_stopout_default_70'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
