# Generated by Django 5.1.6 on 2026-09-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0074_fix_account_product_stopout_70'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_type', models.CharField(choices=[('LIMIT', 'LIMIT'), ('STOP', 'STOP')], max_length=5)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('trigger_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('sl', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('TRIGGERED', 'TRIGGERED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_position_id', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='simulator.tradingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'status'], name='pendord_acc_status_idx'), models.Index(fields=['symbol', 'status'], name='pendord_sym_status_idx'), models.Index(fields=['status', 'expires_at'], name='pendord_status_exp_idx')],
            },
        ),
    ]
