# Generated by Django 5.1.6 on 2026-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0075_pending_order_v2a'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastKnownMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=12, unique=True)),
                ('bid', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ask', models.DecimalField(decimal_places=6, max_digits=18)),
                ('mid', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(max_length=16)),
                ('observed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
