# Generated by Django 5.1.6 on 2026-09-09 16:12
# WITHDRAWAL-SECURITY-EXTENSION-01 — additive only, no destructive ops.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0076_last_known_market_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalEmailOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('ADDRESS_CHANGE', 'Address Change')], max_length=20)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withdraw_all', models.BooleanField(default=False)),
                ('asset', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('wallet_address', models.CharField(max_length=200)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('used', 'Used'), ('expired', 'Expired'), ('locked', 'Locked')], db_index=True, default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='withdrawalemailotpchallenge',
            index=models.Index(fields=['user', 'status'], name='wotp_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalemailotpchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'verified'))), fields=('user',), name='wotp_one_active_per_user'),
        ),
    ]
