# Generated by Django 5.1.6 on 2026-09-09 16:12
# WITHDRAWAL-SECURITY-EXTENSION-01 — additive only, no destructive ops.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0077_withdrawal_email_otp_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedWithdrawalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending_cooldown', 'Pending Cooldown'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('rejected', 'Rejected')], db_index=True, default='pending_cooldown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_withdrawal_wallets', to=settings.AUTH_USER_MODEL)),
                ('created_by_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_wallets_created', to='simulator.withdrawalemailotpchallenge')),
            ],
        ),
        migrations.AddIndex(
            model_name='verifiedwithdrawalwallet',
            index=models.Index(fields=['user', 'asset', 'network', 'status'], name='vww_user_route_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='verifiedwithdrawalwallet',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'asset', 'network'), name='vww_one_active_per_route'),
        ),
        migrations.AddConstraint(
            model_name='verifiedwithdrawalwallet',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending_cooldown')), fields=('user', 'asset', 'network'), name='vww_one_pending_per_route'),
        ),
    ]
