# Generated by Django 5.1.6 on 2026-09-12 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0079_withdrawal_request_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'permissions': [('is_customer_support', 'Is Customer Support agent')], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('COMMISSION', 'COMMISSION'), ('REALIZED_PNL', 'REALIZED_PNL'), ('FEE', 'FEE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('FUNDED_PAYOUT', 'Funded Payout'), ('OWNER_CORRECTION', 'Owner Correction')], max_length=16),
        ),
        migrations.CreateModel(
            name='ManualBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulator.tradingaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerWalletAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_wallet_adjustments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulator.wallet')),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_adjustment', to='simulator.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpsAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_admin_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ops_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_enforcer', True)), name='opsadminprofile_singleton_enforcer_must_be_true'), models.UniqueConstraint(fields=('singleton_enforcer',), name='only_one_ops_admin_profile')],
            },
        ),
        migrations.CreateModel(
            name='OwnerRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('established_by', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_root', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_enforcer', True)), name='ownerroot_singleton_enforcer_must_be_true'), models.UniqueConstraint(fields=('singleton_enforcer',), name='only_one_ownerroot_ever')],
            },
        ),
    ]
