# Generated by Django 5.1.6 on 2026-09-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0081_customer_support_01a_data_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('cookie', 'Cookie'), ('session', 'Session')], max_length=10)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='simulator.referral')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Attribution',
                'verbose_name_plural': 'Referral Attributions',
                'indexes': [models.Index(fields=['referral'], name='simulator_r_referra_46b923_idx')],
            },
        ),
    ]
