# Generated by Django 5.1.6 on 2026-09-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0082_ib_attribution_foundation_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12)),
                ('side', models.CharField(max_length=4)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('execution_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('merged', models.BooleanField()),
                ('entry_path', models.CharField(choices=[('manual_ws', 'Manual WS order'), ('pending_trigger', 'Pending/stop/limit trigger')], max_length=20)),
                ('source_order_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_execution_events', to='simulator.tradingaccount')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_execution_events', to='simulator.position')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='simulator_l_account_daa989_idx')],
            },
        ),
    ]
