# Generated by Django 5.1.6 on 2026-09-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0083_ib_per_lot_execution_event_01'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PER_LOT', 'Per Lot'), ('CHALLENGE_PERCENT', 'Challenge Percent'), ('DEPOSIT_PERCENT', 'Deposit Percent'), ('SPREAD_REVENUE_SHARE', 'Spread Revenue Share'), ('TRADING_COMMISSION_REVENUE_SHARE', 'Trading Commission Revenue Share'), ('CPA_BONUS', 'CPA Bonus')], db_index=True, max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cpa_trigger_event', models.CharField(blank=True, default='', max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_rules_created', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='simulator.referral')),
            ],
            options={
                'verbose_name': 'IB Commission Rule',
                'verbose_name_plural': 'IB Commission Rules',
            },
        ),
        migrations.CreateModel(
            name='IBCommissionObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('PER_LOT', 'Per Lot'), ('CHALLENGE_PERCENT', 'Challenge Percent'), ('DEPOSIT_PERCENT', 'Deposit Percent'), ('SPREAD_REVENUE_SHARE', 'Spread Revenue Share'), ('TRADING_COMMISSION_REVENUE_SHARE', 'Trading Commission Revenue Share'), ('CPA_BONUS', 'CPA Bonus')], max_length=40)),
                ('source_event_type', models.CharField(max_length=40)),
                ('source_event_id', models.BigIntegerField()),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('basis_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('basis_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('applied_fixed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applied_percentage_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CREDITED', 'Credited'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_obligations_approved', to=settings.AUTH_USER_MODEL)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_obligations', to='simulator.referralattribution')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_obligations', to='simulator.referral')),
                ('treasury_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_obligation', to='simulator.treasuryoperationrequest')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='simulator.ibcommissionrule')),
            ],
            options={
                'verbose_name': 'IB Commission Obligation',
                'verbose_name_plural': 'IB Commission Obligations',
            },
        ),
        migrations.AddIndex(
            model_name='ibcommissionrule',
            index=models.Index(fields=['rule_type', 'referral'], name='simulator_i_rule_ty_1b0e55_idx'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='ibrule_fixed_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__gte', 0), _connector='OR'), name='ibrule_percentage_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='ibrule_effective_until_after_from'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_type', 'PER_LOT'), _negated=True), ('fixed_amount__isnull', False), _connector='OR'), name='ibrule_per_lot_requires_fixed_amount'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_type', 'CPA_BONUS'), _negated=True), ('fixed_amount__isnull', False), _connector='OR'), name='ibrule_cpa_bonus_requires_fixed_amount'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_type__in', ['CHALLENGE_PERCENT', 'DEPOSIT_PERCENT', 'SPREAD_REVENUE_SHARE', 'TRADING_COMMISSION_REVENUE_SHARE']), _negated=True), ('percentage__isnull', False), _connector='OR'), name='ibrule_percentage_types_require_percentage'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True)), fields=('rule_type', 'referral'), name='ibrule_one_open_ended_per_type_scope'),
        ),
        migrations.AddIndex(
            model_name='ibcommissionobligation',
            index=models.Index(fields=['referral', 'status'], name='simulator_i_referra_85ed45_idx'),
        ),
        migrations.AddIndex(
            model_name='ibcommissionobligation',
            index=models.Index(fields=['source_event_type', 'source_event_id'], name='simulator_i_source__07e6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='ibcommissionobligation',
            index=models.Index(fields=['status', 'created_at'], name='simulator_i_status_a4c61c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ibcommissionobligation',
            constraint=models.UniqueConstraint(fields=('referral', 'rule_type', 'source_event_type', 'source_event_id'), name='ib_commission_one_obligation_per_event'),
        ),
    ]
