# Generated by Django 5.1.6 on 2026-09-20 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0084_ib_commission_engine_01'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBCommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], default='REVERSAL', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='simulator.ibcommissionobligation')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_adjustments', to='simulator.referral')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_adjustments_rejected', to=settings.AUTH_USER_MODEL)),
                ('treasury_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_commission_adjustment', to='simulator.treasuryoperationrequest')),
            ],
            options={
                'verbose_name': 'IB Commission Adjustment',
                'verbose_name_plural': 'IB Commission Adjustments',
                'indexes': [models.Index(fields=['obligation', 'status'], name='simulator_i_obligat_5c89ff_idx'), models.Index(fields=['referral', 'status'], name='simulator_i_referra_68f4a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ib_adjustment_amount_positive')],
            },
        ),
    ]
