# Generated by Django 5.1.6 on 2026-09-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0085_ib_reversals_fraud_05b_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ibcommissionobligation',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibcommissionobligation',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_obligations_held', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ibcommissionobligation',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ibcommissionobligation',
            name='is_held',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_frozen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='frozen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='referral',
            name='risk_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='IBRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FROZEN', 'Frozen'), ('UNFROZEN', 'Unfrozen'), ('OBLIGATION_HELD', 'Obligation Held'), ('OBLIGATION_RELEASED', 'Obligation Released')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_risk_events_actioned', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='simulator.ibcommissionobligation')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='simulator.referral')),
            ],
            options={
                'verbose_name': 'IB Risk Event',
                'verbose_name_plural': 'IB Risk Events',
                'indexes': [models.Index(fields=['referral', 'created_at'], name='simulator_i_referra_1784d1_idx'), models.Index(fields=['obligation', 'created_at'], name='simulator_i_obligat_af9593_idx')],
            },
        ),
    ]
