# Generated by Django 5.1.6 on 2026-09-21 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0086_ib_risk_holds_07b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ibcommissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__lte', 100), _connector='OR'), name='ibrule_percentage_lte_100'),
        ),
    ]
