# Generated by Django 5.1.6 on 2026-09-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0087_ib_commission_parity_09b1_percentage_bound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerEconomicAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broker_economic_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='economic_adjustment', to='simulator.brokerledger')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='simulator.brokereconomicadjustment')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_economic_adjustments', to='simulator.tradingaccount')),
                ('source_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by_adjustments', to='simulator.brokerledger')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='broker_economic_adjustment_amount_nonzero'), models.CheckConstraint(condition=models.Q(('reverses', models.F('id')), _negated=True), name='broker_economic_adjustment_no_self_reversal')],
            },
        ),
    ]
