# Generated by Django 5.1.6 on 2026-09-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0088_broker_economic_adjustment_02b'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerledger',
            name='source_challenge_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_ledger', to='simulator.challengeenrollment'),
        ),
        migrations.AddConstraint(
            model_name='brokerledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source_challenge_enrollment__isnull', False)), fields=('source_challenge_enrollment', 'revenue_type'), name='uniq_brokerledger_source_challenge_enrollment_revenue_type'),
        ),
    ]
