# Generated by Django 5.1.6 on 2026-09-24 01:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0089_challenge_fee_ledger_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Commercial withdrawal fee, as a percentage of the gross withdrawal amount (e.g. 1.50 = 1.5%).', max_digits=5)),
                ('enabled', models.BooleanField(default=True, help_text='When off, new withdrawals snapshot a 0.00% fee — the fee is not charged.')),
                ('reason', models.TextField(blank=True, default='', help_text='Why this value was set — required by the admin form on every save, free-text audit note.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Fee Config',
                'verbose_name_plural': 'Withdrawal Fee Config',
            },
        ),
        migrations.AddField(
            model_name='brokerledger',
            name='source_withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_ledger', to='simulator.withdrawalrequest'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='brokerledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source_withdrawal__isnull', False)), fields=('source_withdrawal', 'revenue_type'), name='uniq_brokerledger_source_withdrawal_revenue_type'),
        ),
        migrations.AddField(
            model_name='withdrawalfeeconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_fee_config_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
