# Generated by Django 5.1.6 on 2026-09-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0090_withdrawal_economics_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerledger',
            name='source_funded_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_ledger', to='simulator.fundedpayoutrequest'),
        ),
        migrations.AlterField(
            model_name='brokerledger',
            name='revenue_type',
            field=models.CharField(choices=[('COMMISSION', 'Commission'), ('SPREAD', 'Spread'), ('CHALLENGE_FEE', 'Challenge Fee'), ('WITHDRAW_FEE', 'Withdrawal Fee'), ('ADJUSTMENT', 'Adjustment'), ('COUNTERPARTY_PNL', 'Counterparty PnL (B-Book)'), ('FUNDED_PROFIT_SHARE', 'Funded Profit Share')], db_index=True, max_length=24),
        ),
        migrations.AddConstraint(
            model_name='brokerledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source_funded_payout__isnull', False)), fields=('source_funded_payout', 'revenue_type'), name='uniq_brokerledger_source_funded_payout_revenue_type'),
        ),
    ]
