# Generated by Django 5.1.6 on 2026-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0091_funded_broker_cut_04b'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='nowpayments', max_length=32)),
                ('event_fingerprint', models.CharField(max_length=64, unique=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payment_status', models.CharField(blank=True, default='', max_length=40)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
