# Generated by Django 5.1.6 on 2026-09-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0092_payment_webhook_evidence_04c3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerledger',
            name='revenue_type',
            field=models.CharField(choices=[('COMMISSION', 'Commission'), ('SPREAD', 'Spread'), ('CHALLENGE_FEE', 'Challenge Fee'), ('WITHDRAW_FEE', 'Withdrawal Fee'), ('ADJUSTMENT', 'Adjustment'), ('COUNTERPARTY_PNL', 'Counterparty PnL (B-Book)'), ('FUNDED_PROFIT_SHARE', 'Funded Profit Share'), ('PROVIDER_COST', 'Provider / Network Cost')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='ProviderCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('operation_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other')], max_length=12)),
                ('cost_type', models.CharField(choices=[('PROVIDER_SERVICE', 'Provider Service Fee'), ('NETWORK', 'Network Fee'), ('CONVERSION_FX', 'Conversion / FX'), ('OTHER', 'Other')], max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=24)),
                ('currency', models.CharField(max_length=20)),
                ('usd_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quality', models.CharField(choices=[('ACTUAL', 'Actual'), ('ESTIMATED', 'Estimated'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('is_final', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('cost_fingerprint', models.CharField(max_length=64, unique=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by', to='simulator.providercostrecord')),
                ('source_payment_webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_cost_records', to='simulator.paymentwebhookevent')),
                ('source_payout_webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_cost_records', to='simulator.payoutwebhookevent')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='brokerledger',
            name='source_provider_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_ledger', to='simulator.providercostrecord'),
        ),
        migrations.AddConstraint(
            model_name='brokerledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source_provider_cost__isnull', False)), fields=('source_provider_cost', 'revenue_type'), name='uniq_brokerledger_source_provider_cost_revenue_type'),
        ),
    ]
