# Generated by Django 5.1.6 on 2026-09-25 18:07
#
# BBOOK-CLOSE-01 FASE B.1 — adds explicit provenance (enrollment_source) to
# ChallengeEnrollment and revises uniq_active_enrollment_per_user_product to
# exclude ADMIN_GRANT, preserving the historically-proven admin capability
# to grant a second active enrollment while keeping every real purchase
# path (DEPOSIT/WALLET/EXTERNAL) fully protected. See the FASE B.1-A audit
# for the full creator map and rationale.
#
# The RunPython backfill below is evidence-based only, per the exact rule
# authorized in FASE B.1-B:
#   deposit IS NOT NULL                                -> DEPOSIT
#   deposit IS NULL AND external_event_id IS NOT NULL  -> EXTERNAL
#   deposit IS NULL AND external_event_id IS NULL       -> unchanged
#     (already ADMIN_GRANT from the AddField default above — no historical
#     WALLET enrollment is ever inferred without positive evidence).

from django.conf import settings
from django.db import migrations, models


def _backfill_enrollment_source(apps, schema_editor):
    ChallengeEnrollment = apps.get_model('simulator', 'ChallengeEnrollment')
    ChallengeEnrollment.objects.filter(deposit__isnull=False).update(
        enrollment_source='DEPOSIT',
    )
    ChallengeEnrollment.objects.filter(
        deposit__isnull=True, external_event_id__isnull=False,
    ).update(enrollment_source='EXTERNAL')
    # deposit IS NULL AND external_event_id IS NULL: no UPDATE issued —
    # these rows keep the AddField default ('ADMIN_GRANT') set moments
    # earlier by the operation directly above this one in this same
    # migration. Deliberately not touched here.


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0093_provider_cost_normalization_04c4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeenrollment',
            name='enrollment_source',
            field=models.CharField(choices=[('DEPOSIT', 'NowPayments / Deposit'), ('WALLET', 'Internal Wallet'), ('EXTERNAL', 'External Platform'), ('ADMIN_GRANT', 'Admin Grant')], default='ADMIN_GRANT', max_length=16),
        ),
        migrations.RunPython(_backfill_enrollment_source, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='challengeenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PHASE_1', 'PHASE_2', 'FUNDED']), models.Q(('enrollment_source', 'ADMIN_GRANT'), _negated=True)), fields=('user', 'product'), name='uniq_active_enrollment_per_user_product'),
        ),
    ]
