# Generated by Django 5.1.6 on 2026-09-26 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0094_bbook_close01_active_enrollment_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fundedpayoutrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'processing'])), fields=('enrollment',), name='fpr_one_active_request_per_enrollment'),
        ),
    ]
