# Generated by Django 5.1.6 on 2026-09-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0095_bbook_close02_fpr_one_active_per_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
    ]
