# Generated by Django 5.1.6 on 2026-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0096_bbook_pgfix02_auditlog_action_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutattempt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
