# Generated by Django 5.1.6 on 2026-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0097_payoutattempt_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutattempt',
            name='confirmed_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='payoutattempt',
            name='tx_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
