# Generated by Django 5.1.6 on 2026-10-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0098_payoutattempt_confirmed_amount_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerledger',
            name='economic_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
